name: AsureTraits
version: '1.0'
author: SaintQd
main: org.saintqd.asuretraits.AsureTraits
loader: org.saintqd.asuretraits.AsureTraitsLoader
api-version: '26.2'
description: AsureTraits Plugin
dependencies:
  server:
    AsureLib:
      load: BEFORE
      required: true
    MythicMobs:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
    BreweryX:
      load: BEFORE
      required: false
    CMI:
      load: BEFORE
      required: false