name: AsureTraits
version: 1.0
author: SaintQd
main: org.saintqd.asuretraits.AsureTraits
api-version: 26.2
depend: [AsureLib]
softdepend: [MythicMobs, Vault, BreweryX, CMI]
permissions:
  asuretraits.admin:
    description: Access to admin commands.
    default: op